conf:
  image: busybox
  volumes:
    - /etc/voms-admin
  command: true

data:
  image: busybox
  volumes:
    - /var/lib/mysql
  command: true

db:
  image: mariadb:latest
  ports:
    - "3306"
  volumes_from:
    - data

  environment:
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_USER: voms
    MYSQL_PASSWORD: pwd
    MYSQL_DATABASE: voms_test

mail:
  image: jlynn/python-smtp
  ports:
    - "25"

adminserver1:
  image: italiangrid/voms-admin-server
  hostname: dev
  domainname: local.io
  volumes:
      - .:/code:ro
      - ~/.jrebel:/home/voms/.jrebel:rw
      - ~/jrebel:/jrebel:ro
      - /var/log/voms-admin
  volumes_from:
      - conf
  ports:
      - "8443"
      - "1044"
  links:
      - db
      - mail

  environment:
    MAILHOST: mail
    MYSQL_ROOT_PASSWORD: pwd
    # VOMS_DEBUG: y
    # VOMS_DEBUG_PORT: 1044
    # VOMS_DEBUG_SUSPEND: y

    # ENABLE_JREBEL: y
    # VOMS_SKIP_CONFIGURE: y

#adminserver2:
#  image: italiangrid/voms-admin-server
#  hostname: dev
#  domainname: local.io
#  volumes:
#      - .:/code:ro
#      - ~/.jrebel:/home/voms/.jrebel:rw
#      - ~/jrebel:/jrebel:ro
#      - /var/log/voms-admin
#  volumes_from:
#      - conf
#  ports:
#      - "8443"
#      - "1044"
#  links:
#      - db
#      - mail
#
#  environment:
#    MAILHOST: mail
#    MYSQL_ROOT_PASSWORD: pwd
#    # VOMS_DEBUG: y
#    # VOMS_DEBUG_PORT: 1044
#    # VOMS_DEBUG_SUSPEND: y
#
#    # ENABLE_JREBEL: y
#    VOMS_SKIP_CONFIGURE: y
#    #

haproxy:
  image: tutum/haproxy:latest
  hostname: haproxy
  domainname: local.io

  ports:
      - "8443:8443"

  environment:
      BACKEND_PORT: 8443
      FRONTEND_PORT: 8443
      MODE: tcp

  links:
      - adminserver1
      - adminserver2
