conf:
  image: busybox
  volumes:
    - /etc/voms-admin
  command: /bin/true

data:
  image: busybox
  volumes:
    - /var/lib/mysql
  command: /bin/true

db:
  image: mariadb:latest
  ports:
    - "3306"
  volumes_from:
    - data

  environment:
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_USER: voms
    MYSQL_PASSWORD: pwd
    MYSQL_DATABASE: voms_test

mail:
  image: jlynn/python-smtp
  ports:
    - "25"

adminserver:
  image: italiangrid/voms-admin-server
  hostname: dev
  domainname: local.io
  volumes:
      - .:/code:ro
      - ~/.jrebel:/home/voms/.jrebel:rw
      - ~/jrebel:/jrebel:ro
      - /var/log/voms-admin
        # - ~/orgdb:/orgdb:ro

  volumes_from:
      - conf
  ports:
      - "8443:8443"
      - "1044:1044"
      - "6002:6002"
      - "1099:1099"

  links:
      - db
      - mail

  environment:
    MAILHOST: mail
    MYSQL_ROOT_PASSWORD: pwd
    VOMS_DEBUG: y
    # VOMS_DEBUG_SUSPEND: y
    VOMS_PRE_CONFIGURE: y
    # VOMS_SKIP_CONFIGURE: y
    VOMS_UPGRADE_DB: y
    #VOMS_CONFIGURE_OPTIONS: --skip-ca-check --admin-skip-ca-check --disable-membership-expiration-warnings
    ENABLE_JREBEL: y
    ENABLE_JMX: y
